# use this however you see fit. feel free to optionally add either of the following comments to your file
#
# from github.com/sdolenc/debian-matrix
# or
# inspired by github.com/sdolenc/debian-matrix

version: 2.1
jobs:
  download-bats-core:
    docker:
      - image: curlimages/curl
    steps:
      - run:
            command: |
              set -x
              curl -L https://github.com/bats-core/bats-core/tarball/87b16eb | tar xz
              pwd
              ls
              pushd ~
              pwd
              ls
              popd
      - persist_to_workspace:
          root: ~/
          paths:
            - bats-core-bats-core-87b16eb
  buster:
    docker:
      - image: debian:buster-slim
    <<: &commonSteps
      steps:
        - checkout
        - attach_workspace:
            # Must be absolute path or relative path from working_directory
            at: /tmp/bats-core
        - run:
            command: |
              set -x
              bash --version
              df --help
              df --version
              ls /tmp/
              ls /tmp/bats-core
              bash "/tmp/bats-core/install.sh" /usr/local
              command -v bats
  stretch:
    docker:
      - image: debian:stretch-slim
    <<: *commonSteps
  jessie:
    docker:
      - image: debian/eol:jessie
    <<: *commonSteps
  wheezy:
    docker:
      - image: debian/eol:wheezy
    <<: *commonSteps
  squeeze:
    docker:
      - image: debian/eol:squeeze
    <<: *commonSteps
  lenny:
    docker:
      - image: debian/eol:lenny
    <<: *commonSteps
workflows:
  version: 2
  all:
    jobs:
      - download-bats-core
      - buster:
          requires:
            - download-bats-core
      - stretch:
          requires:
            - download-bats-core
      - jessie:
          requires:
            - download-bats-core
      - wheezy:
          requires:
            - download-bats-core
      - squeeze:
          requires:
            - download-bats-core
      - lenny:
          requires:
            - download-bats-core
