version: 2
jobs:
  buster:
    docker:
      - image: debian:buster-slim
    <<: &commonSteps
      steps:
        - checkout
        - run:
            shell: /bin/sh -e
            command: |
              bash --version
  stretch:
    docker:
      - image: debian:stretch-slim
    <<: *commonSteps
  jessie:
    docker:
      - image: debian/eol:jessie
    <<: *commonSteps
  wheezy:
    docker:
      - image: debian/eol:wheezy
    <<: *commonSteps
  squeeze:
    docker:
      - image: debian/eol:squeeze
    <<: *commonSteps
  lenny:
    docker:
      - image: debian/eol:lenny
    <<: *commonSteps
  etch:
    docker:
      - image: debian/eol:etch
    <<: *commonSteps
  sarge:
    docker:
      - image: debian/eol:sarge
    <<: *commonSteps
  woody:
    docker:
      - image: debian/eol:woody
    <<: *commonSteps
  potato:
    docker:
      - image: debian/eol:potato
    <<: *commonSteps
workflows:
  version: 2
  all:
    jobs:
      - buster
      - stretch
      - jessie
      - wheezy
      - squeeze
      - lenny
      - etch
      - sarge
      - woody
      - potato
