version: 2
jobs:
  buster:
    docker:
      - image: sdolenc/debian-circleci:buster
    <<: &commonSteps
      steps:
        - checkout
        - run:
            shell: /bin/sh -e
            command: |
              bash --version
  stretch:
    docker:
      - image: sdolenc/debian-circleci:stretch
    <<: *commonSteps
  jessie:
    docker:
      - image: sdolenc/debian-circleci:jessie
    <<: *commonSteps
  wheezy:
    docker:
      - image: sdolenc/debian-circleci:wheezy
    <<: *commonSteps
  squeeze:
    docker:
      - image: sdolenc/debian-circleci:squeeze
    <<: *commonSteps
  lenny:
    docker:
      - image: sdolenc/debian-circleci:lenny
    <<: *commonSteps
  etch:
    docker:
      - image: sdolenc/debian-circleci:etch
    <<: *commonSteps
  sarge:
    docker:
      - image: sdolenc/debian-circleci:sarge
    <<: *commonSteps
  woody:
    docker:
      - image: sdolenc/debian-circleci:woody
    <<: *commonSteps
  potato:
    docker:
      - image: sdolenc/debian-circleci:potato
    <<: *commonSteps
workflows:
  version: 2
  all:
    jobs:
      - buster
      - stretch
      - jessie
      - wheezy
      - squeeze
      - lenny
      - etch
      - sarge
      - woody
      - potato
