# please use this however you see fit. feel free to add the following comment to your file
#
# from https://github.com/sdolenc/debian-matrix
# or
# inspired by https://github.com/sdolenc/debian-matrix

version: 2
jobs:
  buster:
    docker:
      - image: debian:buster-slim
    <<: &commonSteps
      steps:
        - checkout
        - run:
             # shell is only needed for bash 2.0*. this line can be removed if you're testing 3.0+
            shell: /bin/sh -e
            command: |
              bash --version
  stretch:
    docker:
      - image: debian:stretch-slim
    <<: *commonSteps
  jessie:
    docker:
      - image: debian/eol:jessie
    <<: *commonSteps
  wheezy:
    docker:
      - image: debian/eol:wheezy
    <<: *commonSteps
  squeeze:
    docker:
      - image: debian/eol:squeeze
    <<: *commonSteps
  lenny:
    docker:
      - image: debian/eol:lenny
    <<: *commonSteps
  etch:
    docker:
      - image: debian/eol:etch
    <<: *commonSteps
  sarge:
    docker:
      - image: debian/eol:sarge
    <<: *commonSteps
  woody:
    docker:
      - image: debian/eol:woody
    <<: *commonSteps
  potato:
    docker:
      - image: debian/eol:potato
    <<: *commonSteps
workflows:
  version: 2
  all:
    jobs:
      - buster
      - stretch
      - jessie
      - wheezy
      - squeeze
      - lenny
      - etch
      - sarge
      - woody
      - potato
