# use this however you see fit. feel free to optionally add either of the following comments to your file
#
# from github.com/sdolenc/debian-matrix
# or
# inspired by github.com/sdolenc/debian-matrix

version: 2.1
jobs:
  download-bats-core:
    docker:
      - image: curlimages/curl
    steps:
      - run:
            command: |
              cd /tmp
              curl -L https://github.com/bats-core/bats-core/tarball/87b16eb | tar xz
              mv bats-core-bats-core-87b16eb bats-core
      - persist_to_workspace:
          root: /tmp
          paths:
            - bats-core
  buster:
    docker:
      - image: sdolenc/debian-circleci:buster
    <<: &commonSteps
      steps:
        - checkout
        - attach_workspace:
            at: /tmp
        - run:
            command: |
              set -x
              bash --version
              df --help
              df --version
              bash /tmp/bats-core/install.sh /usr/local
              command -v bats
  stretch:
    docker:
      - image: sdolenc/debian-circleci:stretch
    <<: *commonSteps
  jessie:
    docker:
      - image: sdolenc/debian-circleci:jessie
    <<: *commonSteps
  wheezy:
    docker:
      - image: sdolenc/debian-circleci:wheezy
    <<: *commonSteps
  squeeze:
    docker:
      - image: sdolenc/debian-circleci:squeeze
    <<: *commonSteps
  lenny:
    docker:
      - image: sdolenc/debian-circleci:lenny
    <<: *commonSteps
workflows:
  version: 2
  all:
    jobs:
      - download-bats-core
      - buster:
          requires:
            - download-bats-core
      - stretch:
          requires:
            - download-bats-core
      - jessie:
          requires:
            - download-bats-core
      - wheezy:
          requires:
            - download-bats-core
      - squeeze:
          requires:
            - download-bats-core
      - lenny:
          requires:
            - download-bats-core
