# use this however you see fit. feel free to optionally add either of the following comments to your file
#
# from github.com/sdolenc/debian-matrix
# or
# inspired by github.com/sdolenc/debian-matrix

version: 2.0
jobs:
  download-bats-core:
    environment:
      - bash_unit_test: "https://github.com/bats-core/bats-core"
      - commit: "87b16eb"
    docker:
      - image: curlimages/curl
    working_directory: /tmp
    steps:
      - run:
            command: |
              curl -L "${bash_unit_test}/tarball/${commit}" | tar xz
              mv "bats-core-bats-core-${commit}" bats-core
      - persist_to_workspace:
          root: /tmp
          paths:
            - bats-core
  buster:
    docker:
      - image: sdolenc/debian-circleci:buster
    <<: &commonSteps
      steps:
        - checkout
        - attach_workspace:
            at: /tmp
        - run:
            command: |
              set -x
              bash --version
              df --version
              df --help
              bash /tmp/bats-core/install.sh /usr/local
              command -v bats
  stretch:
    docker:
      - image: sdolenc/debian-circleci:stretch
    <<: *commonSteps
  jessie:
    docker:
      - image: sdolenc/debian-circleci:jessie
    <<: *commonSteps
  wheezy:
    docker:
      - image: sdolenc/debian-circleci:wheezy
    <<: *commonSteps
  squeeze:
    docker:
      - image: sdolenc/debian-circleci:squeeze
    <<: *commonSteps
  lenny:
    docker:
      - image: sdolenc/debian-circleci:lenny
    <<: *commonSteps
workflows:
  version: 2
  all:
    jobs:
      - download-bats-core
      - buster:
          requires:
            - download-bats-core
      - stretch:
          requires:
            - download-bats-core
      - jessie:
          requires:
            - download-bats-core
      - wheezy:
          requires:
            - download-bats-core
      - squeeze:
          requires:
            - download-bats-core
      - lenny:
          requires:
            - download-bats-core
